name: in_app_purchase_android
description: An implementation for the Android platform of the Flutter `in_app_purchase` plugin. This uses the Android BillingClient APIs.
repository: https://github.com/zzhhai/flutter_package/in_app_purchase/in_app_purchase_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 0.2.5+4

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: in_app_purchase
    platforms:
      android:
        package: io.flutter.plugins.inapppurchase
        pluginClass: InAppPurchasePlugin

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface:
    git:
      url: git@github.com:zzhhai/flutter_package.git
      path: flutter_package/in_app_purchase/in_app_purchase_platform_interface
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mockito: 5.4.0
  test: ^1.16.0
